version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: game-mysql
    environment:
      MYSQL_DATABASE: game_db
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: game-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/game_db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpass
    ports:
      - "8080:8080"

volumes:
  db_data: